In [58]:
import torch
import numpy as np

In [59]:
torch.tensor([[2,3,5],[1,2,9]])

tensor([[2, 3, 5],
        [1, 2, 9]])

In [60]:
a=torch.rand((3,5))
a

tensor([[0.2751, 0.7963, 0.7141, 0.6525, 0.4518],
        [0.6325, 0.4610, 0.8469, 0.9125, 0.8948],
        [0.5168, 0.9710, 0.8381, 0.3682, 0.9449]])

In [61]:
a.shape

torch.Size([3, 5])

In [62]:
a=torch.rand((2,2))
b=torch.rand((2,2))
torch.matmul(a,b)

tensor([[0.0492, 0.0525],
        [0.3643, 0.9577]])

In [63]:
a_torch=torch.zeros(2,2)
a_torch


tensor([[0., 0.],
        [0., 0.]])

In [64]:
b_torch=torch.ones(2,2)
b_torch

tensor([[1., 1.],
        [1., 1.]])

In [65]:
c_torch=torch.eye(3)
c_torch

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [69]:
c_numpy=np.identity(2)
d_torch =torch.from_numpy(c_numpy)
d_torch

tensor([[1., 0.],
        [0., 1.]], dtype=torch.float64)

In [70]:
# element wise multiplication just * 

In [71]:
import torch 
a=torch.Tensor([2])
b=torch.Tensor([-4])
c=torch.Tensor([-2])
d=torch.Tensor([2])


In [72]:
e=a+b
f=c*d

In [73]:
g=e*f

In [74]:
print(e,f,g)

tensor([-2.]) tensor([-4.]) tensor([8.])


# Backpropagation and autodifferentiation 

In [78]:
import torch 
x=torch.tensor(-3.,requires_grad=True)
y=torch.tensor(5., requires_grad=True)
z=torch.tensor(-2.,requires_grad=True)
q=x+y
f=q*z
f.backward()
print("Gradient of z is: " + str(z.grad))
print("Gradient of y is: " + str(y.grad))
print("Gradient of x is: " + str(x.grad))


Gradient of z is: tensor(2.)
Gradient of y is: tensor(-2.)
Gradient of x is: tensor(-2.)


In [82]:
input_layer = torch.rand(10)
w1=torch.rand(10,20)
w2=torch.rand(20,20)
w3=torch.rand(20,4)
h1=torch.matmul(input_layer,w1)
h2=torch.matmul(h1,w2)
output_layer=torch.matmul(h2,w3)
print(output_layer)

tensor([351.7537, 361.5762, 393.0299, 326.8207])


In [87]:
import torch.nn as nn 
class Net(nn.Module):
    def __init__(self): 
        super(Net,self).__init__()
        self.fc1=nn.Linear(10,20)
        self.fc2=nn.Linear(20,20)
        self.output=nn.Linear(20,4)
    def forward(self,x):
        x=self.fc1(x)
        x=self.fc2(x)
        x=self.output(x)
        return x
input_layer= torch.rand(10)
net=Net()
result=net(input_layer)

In [88]:
# (28,28) - 784 pixels 


* Images of size (28,28) - 784 pixels 
* hidden layer (200 units) output layer (10 classes)
* weight_1 = torch.rand(784, 200)
* weight_2 = torch.rand(200, 10)
* 784 the input layer 
* 200 hidden units
* 10 units outputs. 


In [89]:
output_layer=torch.matmul(input_layer, weight)


NameError: name 'weight' is not defined