In [18]:
import torch
import numpy as np

In [19]:
x=[12,23,34,56,67,78]
torch.is_tensor(x)

False

In [20]:
torch.is_storage(x)

False

In [21]:
y=torch.randn(1,2,3,4,5)

In [22]:
torch.is_tensor(y)

True

In [23]:
torch.zeros(4,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
torch.numel(torch.zeros(4,4))

16

In [25]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [26]:
torch.eye(5,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

In [28]:
x1=np.array(x)

In [29]:
torch.from_numpy(x1)

tensor([12, 23, 34, 56, 67, 78], dtype=torch.int32)

In [30]:
x1

array([12, 23, 34, 56, 67, 78])

In [32]:
torch.from_numpy(x1)

tensor([12, 23, 34, 56, 67, 78], dtype=torch.int32)

In [33]:
torch.from_numpy(x1)

tensor([12, 23, 34, 56, 67, 78], dtype=torch.int32)

In [34]:
torch.linspace(2,10,steps=25) #linear spacing

tensor([ 2.0000,  2.3333,  2.6667,  3.0000,  3.3333,  3.6667,  4.0000,  4.3333,
         4.6667,  5.0000,  5.3333,  5.6667,  6.0000,  6.3333,  6.6667,  7.0000,
         7.3333,  7.6667,  8.0000,  8.3333,  8.6667,  9.0000,  9.3333,  9.6667,
        10.0000])

In [35]:
torch.logspace(start=10, end=10, steps=15)

tensor([1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10,
        1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10, 1.0000e+10,
        1.0000e+10, 1.0000e+10, 1.0000e+10])

In [36]:
torch.rand(10)

tensor([0.0410, 0.4107, 0.2754, 0.1223, 0.0938, 0.6652, 0.4284, 0.5537, 0.4974,
        0.3561])

In [37]:
torch.rand(4,5)

tensor([[0.8011, 0.1240, 0.0294, 0.1350, 0.3207],
        [0.0902, 0.1064, 0.6196, 0.2748, 0.1869],
        [0.9929, 0.4231, 0.3554, 0.2406, 0.3232],
        [0.7471, 0.2783, 0.7884, 0.0267, 0.3696]])

In [38]:
torch.randn(10)

tensor([-0.7603,  1.6569, -0.7586,  0.3999, -0.9979,  0.9851,  1.1839, -0.8034,
         1.9733, -0.8049])

In [39]:
torch.randn(4,5)

tensor([[-0.4830,  0.1980,  2.5265,  2.1738,  0.4932],
        [ 0.0677, -0.0607, -0.2312, -0.7934, -0.2670],
        [-0.4596, -0.0288, -0.8613,  0.8538,  0.4771],
        [-0.4694, -0.5088, -0.3096, -0.4772, -0.3880]])

In [41]:
torch.randperm(10)
#random permutation

tensor([1, 3, 6, 9, 5, 0, 4, 7, 8, 2])

In [42]:
#usage of range function 
torch.arange(10,40,2)

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [43]:
torch.arange(10,40)

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [45]:
d=torch.randn(4,5)
d

tensor([[ 0.6857,  0.1674,  0.2725, -0.0157, -0.6181],
        [-0.5895, -0.7014, -1.6239,  0.0949,  1.3449],
        [ 0.7677,  0.6818, -1.4667,  1.7836,  0.2956],
        [-1.6690, -1.2410,  0.0695,  0.1624, -1.3232]])

In [46]:
torch.argmin(d,dim=1)

tensor([4, 2, 2, 0])

In [47]:
torch.argmax(d,dim=1)

tensor([0, 4, 3, 3])

# Rows and columns 2D tensor

In [48]:
torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [49]:
torch.zeros(10)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
x=torch.randn(4,5)
x

tensor([[-1.0455, -1.0968,  0.2215, -1.0376,  1.5177],
        [-0.1023,  0.0683,  0.4956, -1.2352, -0.3763],
        [ 0.7779,  0.8377,  0.6843,  2.1391,  0.0605],
        [-0.0875,  0.2875, -0.1476, -1.1903,  1.3517]])

Concatenate two tensors

In [52]:
#concatenate two tensors 
torch.cat((x,x))

tensor([[-1.0455, -1.0968,  0.2215, -1.0376,  1.5177],
        [-0.1023,  0.0683,  0.4956, -1.2352, -0.3763],
        [ 0.7779,  0.8377,  0.6843,  2.1391,  0.0605],
        [-0.0875,  0.2875, -0.1476, -1.1903,  1.3517],
        [-1.0455, -1.0968,  0.2215, -1.0376,  1.5177],
        [-0.1023,  0.0683,  0.4956, -1.2352, -0.3763],
        [ 0.7779,  0.8377,  0.6843,  2.1391,  0.0605],
        [-0.0875,  0.2875, -0.1476, -1.1903,  1.3517]])

In [53]:
torch.cat((x,x,x),1)

tensor([[-1.0455, -1.0968,  0.2215, -1.0376,  1.5177, -1.0455, -1.0968,  0.2215,
         -1.0376,  1.5177, -1.0455, -1.0968,  0.2215, -1.0376,  1.5177],
        [-0.1023,  0.0683,  0.4956, -1.2352, -0.3763, -0.1023,  0.0683,  0.4956,
         -1.2352, -0.3763, -0.1023,  0.0683,  0.4956, -1.2352, -0.3763],
        [ 0.7779,  0.8377,  0.6843,  2.1391,  0.0605,  0.7779,  0.8377,  0.6843,
          2.1391,  0.0605,  0.7779,  0.8377,  0.6843,  2.1391,  0.0605],
        [-0.0875,  0.2875, -0.1476, -1.1903,  1.3517, -0.0875,  0.2875, -0.1476,
         -1.1903,  1.3517, -0.0875,  0.2875, -0.1476, -1.1903,  1.3517]])

In [54]:
torch.cat((x,x), 0 )

tensor([[-1.0455, -1.0968,  0.2215, -1.0376,  1.5177],
        [-0.1023,  0.0683,  0.4956, -1.2352, -0.3763],
        [ 0.7779,  0.8377,  0.6843,  2.1391,  0.0605],
        [-0.0875,  0.2875, -0.1476, -1.1903,  1.3517],
        [-1.0455, -1.0968,  0.2215, -1.0376,  1.5177],
        [-0.1023,  0.0683,  0.4956, -1.2352, -0.3763],
        [ 0.7779,  0.8377,  0.6843,  2.1391,  0.0605],
        [-0.0875,  0.2875, -0.1476, -1.1903,  1.3517]])

In [55]:
a=torch.randn(4,4)
print(a)

tensor([[-1.6800,  0.5274,  1.4102, -0.0094],
        [ 0.4184,  1.7037,  0.0606, -2.2732],
        [ 0.4244, -2.3179, -0.1782, -0.6730],
        [-1.2695,  1.1779, -0.1961, -0.7307]])


In [56]:
torch.chunk(a,2)

(tensor([[-1.6800,  0.5274,  1.4102, -0.0094],
         [ 0.4184,  1.7037,  0.0606, -2.2732]]),
 tensor([[ 0.4244, -2.3179, -0.1782, -0.6730],
         [-1.2695,  1.1779, -0.1961, -0.7307]]))

In [57]:
torch.chunk(a,2,0)

(tensor([[-1.6800,  0.5274,  1.4102, -0.0094],
         [ 0.4184,  1.7037,  0.0606, -2.2732]]),
 tensor([[ 0.4244, -2.3179, -0.1782, -0.6730],
         [-1.2695,  1.1779, -0.1961, -0.7307]]))

In [58]:
torch.chunk(a,2,1)

(tensor([[-1.6800,  0.5274],
         [ 0.4184,  1.7037],
         [ 0.4244, -2.3179],
         [-1.2695,  1.1779]]),
 tensor([[ 1.4102, -0.0094],
         [ 0.0606, -2.2732],
         [-0.1782, -0.6730],
         [-0.1961, -0.7307]]))

In [59]:
torch.Tensor([[11,12], [23,24]])

tensor([[11., 12.],
        [23., 24.]])

In [60]:
torch.gather(torch.Tensor([[11,12], [23,24]]),1, torch.LongTensor([[0,0],[1,0]]))

tensor([[11., 11.],
        [24., 23.]])

In [61]:
torch.LongTensor([[0,0],[1,0]])

tensor([[0, 0],
        [1, 0]])

In [62]:
a=torch.randn(4,4)
print(a)

tensor([[-1.1847,  0.6204,  0.6979, -0.5902],
        [-0.9301, -0.6507,  0.1966, -0.1052],
        [ 0.3154,  0.9219, -0.6209, -0.0070],
        [ 1.8191,  0.0335,  1.1681, -1.0186]])


In [65]:
indices =torch.LongTensor([0,2])
torch.index_select(a,0,indices)

tensor([[-1.1847,  0.6204,  0.6979, -0.5902],
        [ 0.3154,  0.9219, -0.6209, -0.0070]])

In [66]:
torch.index_select(a,1,indices)

tensor([[-1.1847,  0.6979],
        [-0.9301,  0.1966],
        [ 0.3154, -0.6209],
        [ 1.8191,  1.1681]])

In [67]:
#identify null input tensors using nonzero function 
torch.nonzero(torch.tensor([10,00,23,0,0.0]))

tensor([[0],
        [2]])

In [68]:
#split tensor into small chunks 
torch.split(torch.tensor([12,21,34,32,45,54,56,65]),2)

(tensor([12, 21]), tensor([34, 32]), tensor([45, 54]), tensor([56, 65]))

In [69]:
torch.split(torch.tensor([12,21,34,32,45,54,56,65]),3)

(tensor([12, 21, 34]), tensor([32, 45, 54]), tensor([56, 65]))

In [70]:
x

tensor([[-1.0455, -1.0968,  0.2215, -1.0376,  1.5177],
        [-0.1023,  0.0683,  0.4956, -1.2352, -0.3763],
        [ 0.7779,  0.8377,  0.6843,  2.1391,  0.0605],
        [-0.0875,  0.2875, -0.1476, -1.1903,  1.3517]])

In [72]:
x.t() #transpose

tensor([[-1.0455, -0.1023,  0.7779, -0.0875],
        [-1.0968,  0.0683,  0.8377,  0.2875],
        [ 0.2215,  0.4956,  0.6843, -0.1476],
        [-1.0376, -1.2352,  2.1391, -1.1903],
        [ 1.5177, -0.3763,  0.0605,  1.3517]])

In [73]:
x.transpose(1,0)

tensor([[-1.0455, -0.1023,  0.7779, -0.0875],
        [-1.0968,  0.0683,  0.8377,  0.2875],
        [ 0.2215,  0.4956,  0.6843, -0.1476],
        [-1.0376, -1.2352,  2.1391, -1.1903],
        [ 1.5177, -0.3763,  0.0605,  1.3517]])

In [74]:
x

tensor([[-1.0455, -1.0968,  0.2215, -1.0376,  1.5177],
        [-0.1023,  0.0683,  0.4956, -1.2352, -0.3763],
        [ 0.7779,  0.8377,  0.6843,  2.1391,  0.0605],
        [-0.0875,  0.2875, -0.1476, -1.1903,  1.3517]])

In [76]:
torch.unbind(x,1) #dim=1 remove a column 

(tensor([-1.0455, -0.1023,  0.7779, -0.0875]),
 tensor([-1.0968,  0.0683,  0.8377,  0.2875]),
 tensor([ 0.2215,  0.4956,  0.6843, -0.1476]),
 tensor([-1.0376, -1.2352,  2.1391, -1.1903]),
 tensor([ 1.5177, -0.3763,  0.0605,  1.3517]))

In [77]:
torch.unbind(x) #dim=0 removed a row 

(tensor([-1.0455, -1.0968,  0.2215, -1.0376,  1.5177]),
 tensor([-0.1023,  0.0683,  0.4956, -1.2352, -0.3763]),
 tensor([0.7779, 0.8377, 0.6843, 2.1391, 0.0605]),
 tensor([-0.0875,  0.2875, -0.1476, -1.1903,  1.3517]))

In [78]:
x

tensor([[-1.0455, -1.0968,  0.2215, -1.0376,  1.5177],
        [-0.1023,  0.0683,  0.4956, -1.2352, -0.3763],
        [ 0.7779,  0.8377,  0.6843,  2.1391,  0.0605],
        [-0.0875,  0.2875, -0.1476, -1.1903,  1.3517]])

In [79]:
# adding a value to the existing tensor, scalar addition 
torch.add(x,20)

tensor([[18.9545, 18.9032, 20.2215, 18.9624, 21.5177],
        [19.8977, 20.0683, 20.4956, 18.7648, 19.6237],
        [20.7779, 20.8377, 20.6843, 22.1391, 20.0605],
        [19.9125, 20.2875, 19.8524, 18.8097, 21.3517]])

In [80]:
x

tensor([[-1.0455, -1.0968,  0.2215, -1.0376,  1.5177],
        [-0.1023,  0.0683,  0.4956, -1.2352, -0.3763],
        [ 0.7779,  0.8377,  0.6843,  2.1391,  0.0605],
        [-0.0875,  0.2875, -0.1476, -1.1903,  1.3517]])

In [81]:
#scalar multiplication 
torch.mul(x,2)

tensor([[-2.0910, -2.1937,  0.4431, -2.0753,  3.0354],
        [-0.2046,  0.1366,  0.9912, -2.4703, -0.7526],
        [ 1.5558,  1.6754,  1.3686,  4.2781,  0.1211],
        [-0.1750,  0.5749, -0.2951, -2.3806,  2.7034]])

In [82]:
intercept =torch.randn(1)
intercept

tensor([1.7852])

In [83]:
x=torch.randn(2,2)
x

tensor([[ 2.8261,  1.1392],
        [-0.0210,  0.1057]])

In [84]:
beta=0.7456
beta

0.7456

In [85]:
torch.mul(intercept,x)

tensor([[ 5.0452,  2.0336],
        [-0.0375,  0.1888]])

In [86]:
torch.mul(x,beta)

tensor([[ 2.1071,  0.8494],
        [-0.0157,  0.0788]])

In [87]:
# y= intercept + beta*x 
torch.add(torch.mul(intercept,x), torch.mul(x,beta))


tensor([[ 7.1523,  2.8830],
        [-0.0532,  0.2676]])

In [88]:
torch.manual_seed(1234)
torch.randn(5,5)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817,  0.0539],
        [ 0.6684, -0.0597, -0.4675, -0.2153, -0.7141],
        [-1.0831, -0.5547,  0.9717, -0.5150,  1.4255],
        [ 0.7987, -1.4949,  1.4778, -0.1696, -0.9919],
        [-1.4569,  0.2563, -0.4030,  0.4195,  0.9380]])

In [89]:
torch.manual_seed(1234)
torch.ceil(torch.randn(5,5))

tensor([[-0., -0.,  1., -0.,  1.],
        [ 1., -0., -0., -0., -0.],
        [-1., -0.,  1., -0.,  2.],
        [ 1., -1.,  2., -0., -0.],
        [-1.,  1., -0.,  1.,  1.]])

In [90]:
torch.manual_seed(1234)
torch.floor(torch.randn(5,5))

tensor([[-1., -1.,  0., -1.,  0.],
        [ 0., -1., -1., -1., -1.],
        [-2., -1.,  0., -1.,  1.],
        [ 0., -2.,  1., -1., -1.],
        [-2.,  0., -1.,  0.,  0.]])

In [91]:
#truncate the values in range 0 - 1
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3, max=0.4)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  0.4000],
        [ 0.0000, -0.3000,  0.4000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [92]:
#truncate with lower limit 
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), min=-0.3)

tensor([[-0.3000, -0.3000,  0.0000, -0.3000,  0.0000],
        [ 0.0000, -0.3000, -0.3000, -0.3000, -0.3000],
        [-0.3000, -0.3000,  0.0000, -0.3000,  1.0000],
        [ 0.0000, -0.3000,  1.0000, -0.3000, -0.3000],
        [-0.3000,  0.0000, -0.3000,  0.0000,  0.0000]])

In [93]:
#truncate with upper limit 
torch.manual_seed(1234)
torch.clamp(torch.floor(torch.randn(5,5)), max=0.3)

tensor([[-1.0000, -1.0000,  0.0000, -1.0000,  0.0000],
        [ 0.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [-2.0000, -1.0000,  0.0000, -1.0000,  0.3000],
        [ 0.0000, -2.0000,  0.3000, -1.0000, -1.0000],
        [-2.0000,  0.0000, -1.0000,  0.0000,  0.0000]])

In [94]:
# compute exponential of a tensor 
torch.exp(x)

tensor([[16.8789,  3.1241],
        [ 0.9792,  1.1115]])

In [95]:
np.exp(x)

tensor([[16.8789,  3.1241],
        [ 0.9792,  1.1115]])

In [96]:
torch.add(x,10)

tensor([[12.8261, 11.1392],
        [ 9.9790, 10.1057]])

In [97]:
torch.frac(torch.add(x,10))

tensor([[0.8261, 0.1392],
        [0.9790, 0.1057]])

In [98]:
#compute log of the values in a tensor 
x

tensor([[ 2.8261,  1.1392],
        [-0.0210,  0.1057]])

In [100]:
torch.log(x)

tensor([[ 1.0389,  0.1303],
        [    nan, -2.2468]])

In [101]:
torch.pow(x,2)

tensor([[7.9866e+00, 1.2977e+00],
        [4.4134e-04, 1.1181e-02]])

In [102]:
#sigmoid of the input tensor 
x

tensor([[ 2.8261,  1.1392],
        [-0.0210,  0.1057]])

In [103]:
torch.sigmoid(x)

tensor([[0.9441, 0.7575],
        [0.4947, 0.5264]])

In [104]:
torch.sqrt(x)

tensor([[1.6811, 1.0673],
        [   nan, 0.3252]])